### PR TITLE
Demo update

### PR DESCRIPTION
**Pull request by Antoni-Robotec**
An update to the demo so that it's compatible with the latest o3de-extras stabilization branch.

Includes the changes from https://github.com/o3de/ROSConDemo/pull/249, https://github.com/o3de/ROSConDemo/pull/259, https://github.com/o3de/ROSConDemo/pull/237 and https://github.com/o3de/ROSConDemo/pull/240, so those PRs can be closed when this is merged.

### CODE REVIEW

**Comment by jhanca-robotecai** [comment]
Please double-check with the `stabilization` branch as well (both `o3de` and `o3de-extras`). Thanks.

**Comment by Antoni-Robotec** [comment]
> Please double-check with the `stabilization` branch as well (both `o3de` and `o3de-extras`). Thanks.

In the current version it definitely won't work with them as it requires https://github.com/o3de/o3de-extras/pull/492, which isn't even in the o3de-extras development branch yet.
We can remove the usage of the feature from https://github.com/o3de/o3de-extras/pull/492, but that increases jitteriness of the Kraken. I'll also investigate the possibility of switching to articulation links, which should solve the problem, but as Michał noticed, the lack of support for connections between classic joints and articulation links in o3de (https://github.com/o3de/o3de/issues/16188) will be an issue.

**Comment by jhanca-robotecai** [comment]
@michalpelka could you please confirm if we can close this PR? I assume so based on your comment in #262.

**Comment by jhanca-robotecai** [comment]
Changes from this PR were integrated in #262, this PR is outdated. Closing without removing the source branch. Please reopen if necessary.

**Pull request closed without merging**
