### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by floroeske**
Change Gem::AtomLyIntegration_CommonFeatures.Editor.Static to Gem::CommonFeaturesAtom.Editor.Static to match latest o3de-extras https://github.com/o3de/o3de-extras/commit/bbb0da75e6b21216b8dd81c6d95f772390e7613e.

### CODE REVIEW

**Review by jhanca-robotecai — COMMENTED** [review]
Thank you for your contribution, but we prefer to keep the demo in sync with official `o3de` releases. As indicated in the [readme file](https://github.com/o3de/ROSConDemo/blob/34051e129a05c7b2740017fd0513985099e57241/README.md?plain=1#L60), this demo is targeting `main` branches of both `o3de` and `o3de-extras`. This PR should be closed until the next release in February 2024.

Edit: The decision about keeping all demos in sync with `main` branches is justified by the fact that, currently, we do not have the resources to keep them up to date with `o3de` development. Apologies for the confusing branch naming, we will keep it in mind and fix it after the upcoming point release.

**Comment by floroeske** [comment]
No problem. Thanks for clearing that up.

It wasn't clear to me which branches of o3de, o3de-extras and ROSConDemo are supposed to work together. The ROSConDemo readme on the main branch states, use the development branch (https://github.com/o3de/ROSConDemo/blob/main/README.md?plain=1#L58). I guess that created a bit of confusion. So I just used development everywhere.

I'll try again with o3de (main), o3de-extras(main) and ROSConDemo(development).

**Comment by jhanca-robotecai** [comment]
Thank you for pointing that out, it is a mistake on our side. Please use the `development` branch of this demo, the main branch is one year old and, most probably, will not work correctly. I will fix this after `o3de` point release (next week).

**Comment by jhanca-robotecai** [comment]
One more comment: it should be possible to run this demo from the docker files. Those were checked recently.

**Pull request closed without merging**
