### PR TITLE
Leaf animation - TreeActor_Anime_one Prefab has animation an triggers to make leafs fall.

### PR DESCRIPTION
**Pull request by shawstar**
https://user-images.githubusercontent.com/87207603/195938013-dfbcb43f-ce57-4f65-a98d-4a9717b21dfc.mp4

Apples will not disappear as this is controlled somewhere other than this prefab.

When the Apple Arm Vacuum (This will need a collider like below, triggers the target area over the apple, will the leafs fall down and the tree shake. 
image

Example of one target getting hit:

Uploading TreePickAnimation.mp4…

### CODE REVIEW

**Comment by adamdbrw** [comment]
I can try this one on my machine if we still want it included. @shawstar this PR probably needs to be rebased. Are you able to test it on Linux?

**Comment by shawstar** [comment]
> I can try this one on my machine if we still want it included. @shawstar this PR probably needs to be rebased. Are you able to test it on Linux?

I might be able to test soon as I get my Linux box running, Still waiting for some parts I order to come in.

**Comment by adamdbrw** [comment]
@shawstar not sure what to do with this PR. On one hand, you did some cool work for Windows. On the other, we certainly need it working on Linux to be viable. What is your opinion?

**Comment by shawstar** [comment]
I am still stuck in limbo until I find drivers for a wifi USB for my Linux box. If this is no longer an important feature that is not needed. We can delete this PR. If it is still needed, let me know.

**Comment by adamdbrw** [comment]
@shawstar This is not needed as we have a complete demo without it. It is just a shame to waste it in my opinion. I was wondering whether we could help by running it on our side and trying to debug the issue with Asset Manager together?
@michalpelka do you think it is a feasible approach?

**Pull request closed without merging**
